---
- name: Environmet Specific Machine Settings
  hosts: all

  tasks:
    - name: Include tasks for {{ env | default(dev) }}
      ansible.builtin.include_tasks:
        file: "./tasks/{{ env | default(dev) }}-vm_settings.yml"
