---
- name: Fix Web App
  hosts: "{{ ansible_eda.event.url_check.url | ansible.builtin.urlsplit("hostname") }}"
  gather_facts: false  

  tasks:
    - name: Start Web service
      ansible.builtin.systemd:
        name: nginx
        state: started
