---
- name: Fix Web App
  hosts: all
  gather_facts: false  

  tasks:
    - name: Host IP
      ansible.builtin.debug: 
        msg: "{{ ansible_eda.event.url_check.url | ansible.builtin.urlsplit('hostname') | default('production')}}"
    
    - name: Start Web service
      ansible.builtin.systemd:
        name: nginx
        state: started
