---
- name: Record config state
  ansible.builtin.copy:
    content: 'Config state commit: {{ ansible_eda.event.payload.after }}'
    dest: /etc/mine.conf
    mode: '0644'

- name: Set rsyslog
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    line: "*.*    /var/log/custom_logs"
  register: rsyslog_status

- name: Restart rsyslog service
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
  when: rsyslog_status.changed

- name: Stop firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: stopped
    enabled: false
