---
- name: Kafka With OpenAI
  hosts: all
  sources:
    - name: Kafka source
      ansible.eda.kafka:
        host: 10.28.20.23
        port: 9092
        topic: jskorzyn

  rules:
    - name: Get Payload Info
      condition:
        all:
#          - event.body is defined
          - body is search("mybrokenapp.service", ignorecase=true)
          - body is search("Failed", ignorecase=true)
      actions:
        - debug:
            msg: "{{ body }}"

        # - run_job_template:
        #     name: LLM - Failed Job Data
        #     organization: MackNet
