---
- name: Kafka With OpenAI
  hosts: all
  sources:
    - name: Kafka source
      ansible.eda.kafka:
        host: 10.28.20.23
        port: 9092
        topic: jskorzyn

  rules:
    - name: Get Payload Info
      condition: event.body is defined
#        all:
#          - event.payload.status == "failed"
      actions:
        - debug:
            msg: "{{ event.payload }}"

        # - run_job_template:
        #     name: LLM - Failed Job Data
        #     organization: MackNet
