---
- name: Kafka With OpenAI
  hosts: all
  sources:
    - name: Kafka source
      ansible.eda.kafka:
        host: 10.28.20.23
        port: 9092
        topic: jskorzyn

  rules:
    - name: Get Payload Info
      condition:
        all:
          - event.body is defined
          - event.body is search("error", ignorecase=true)
#          - event.body == "mybrokenapp.service: Failed with result 'exit-code'"
#          - event.body is search("error", ignorecase=true)
      actions:
        - debug:
            msg: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAA {{ event.body }} BBBBBBBBBBBBBBBBBBBBBBBBBB"

        # - run_job_template:
        #     name: LLM - Failed Job Data
        #     organization: MackNet
