---
- name: Check Web URL
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://10.28.69.194:8080
        delay: 60
  rules:
    # - name: Web App is down
    #   condition:
    #     event.url_check.status == "down"
    #   action:
    #     debug:
    #       msg: "WEB IS DOWN"

    - name: Fix Web App
      condition:
        event.url_check.status == "down"
      action:
        run_job_template:
          name: Web App Fix
          organization: Default
