---
- name: Check Web URL
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://10.28.69.194:8080
        delay: 10
  rules:
    - name: Fix Web App
      condition:
        event.url_check.status == "down"
      action:
        run_job_template:
          name: Web App Fix
          organization: Default
