---
- name: Check Web URL
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://10.28.69.250:8080
        delay: 10
  rules:
    - name: Web App is down
      condition: 
        event.url_check.status == "down"
      action:
        debug:
          msg: "WEB IS DOWN"
#       run_playbook:
#         name: redeploy_mobile_app.yml
