---
- name: Webhook from curl
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Test action
      condition: event.payload.message == "test"
      action:
        debug:
